repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: trailing-whitespace # trims trailing whitespace.
    # -   id: name-tests-test # verifies that test files are named correctly.

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff
    rev: stable
    hooks:
      - id: ruff

  # - repo: local
  #   hooks:
  #     - id: unit-tests
  #       name: Running unit tests.
  #       language: system
  #       entry: make tests-unit
