[project]
name = "htrflow"
version = "0.0.1.dev0"
description = "short description of project."
readme = "docs/README.md"
requires-python = ">=3.10"
authors = [{ name = "Riksarkivet" }]
license = { text = "MIT" }
classifiers = [
    "Intended Audience :: Science/Research",
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
    "pynvml == 11.5.0",
    "huggingface-hub",
    "openmim==0.3.9",
    "mmengine==0.9.1",
    "mmcv",
    "mmdet",
    "mmocr",
    "yapf==0.40.1",
    "pandas",
    "numpy",
    "opencv-python",
    "Jinja2==3.1.3",
    "transformers",
    "datasets",
    "requests",
    "accelerate",
]
# dynamic = ["version"]


[project.urls]
homepage = "https://Riksarkivet/htrflow"
documentation = "https://readthedocs.org"
repository = "https://github.com"
changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.optional-dependencies]

rapids11 = [
    "cudf-cu11",
    "dask-cudf-cu11",
    "cuml-cu11",
    "cugraph-cu11",
    "cuspatial-cu11",
    "cuproj-cu11",
    "cuxfilter-cu11",
    "cucim",
]

rapids12 = [
    "cudf-cu12",
    "dask-cudf-cu12",
    "cuml-cu12",
    "cugraph-cu12",
    "cuspatial-cu12",
    "cuproj-cu12",
    "cuxfilter-cu12",
    "cucim",
]

[tool.hatch]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.envs.test]
dependencies = [
    "pytest",
    "pytest-cov[all]",
    "ruff",
    "black",
    "mypy",
    "coverage",
    "isort",
    "python-dotenv",
]

[[tool.hatch.envs.test.matrix]]
rapids = ["none", "rapids11", "rapids12"]
cuda = ["none", "some-cuda-version", "some-other-cuda-version"]

[tool.hatch.envs.test.rapids11]
dependencies = ["cudf-cu11"]

[tool.hatch.envs.test.rapids12]
dependencies = ["cudf-cu12"]

[tool.hatch.build.targets.sdist]
exclude = [
        "/.github",
]

[tool.pytest.ini_options]
addopts = "-v --cov=htrflow"
testpaths = ["tests/unit"]

[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.black]
line-length = 119
target-version = ['py10']

[tool.ruff]
ignore = ["C901", "E501", "E741", "W605", "I001"]
select = ["C", "E", "F", "I", "W"]
line-length = 119

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["htrflow"]
