# Demo pipeline for running text
# Run with python3 main.py demo.yaml <input directory>

steps:

# Region segmentation
- step: Segmentation
  settings:
    model: rtmdet
    model_settings:
       model: Riksarkivet/rtmdet_regions
       revision: 868f58e096654ceac9646a467bae55d38f757447
    generation_settings:
       image_scaling_factor: 0.3
       batch_size: 32

# Line segmentation
- step: Segmentation
  settings:
    model: rtmdet
    model_settings:
       model: Riksarkivet/rtmdet_lines
    generation_settings:
       image_scaling_factor: 0.4
       batch_size: 16
       nms_downscale: 0.5

- step: TextRecognition
  settings:
    model: WordLevelTrocr
    model_settings:
       model: Riksarkivet/trocr-base-handwritten-swe
    generation_settings:
       batch_size: 64
       num_beams: 1

- step: ReadingOrderMarginalia
  settings:
    two_page: always

- step: RemoveLowTextConfidencePages
  settings:
    threshold: 0.99

- step: RemoveLowTextConfidenceLines
  settings:
    threshold: 0.95

# Export to Alto and Page XML 
- step: Export
  settings:
    dest: outputs/alto
    format: alto

- step: Export
  settings:
    dest: outputs/page
    format: page

# Sets label format to regionX_lineY_wordZ
labels:
  level_labels:
    - region
    - line
    - word
  sep: _
  template: "{label}{number}"
