# .azure-pipelines/tox.yaml
trigger:
  branches:
    include:
      - main

pool:
  name: k8s

resources:
  repositories:
    - repository: tox
      type: github
      endpoint: github
      name: tox-dev/azure-pipelines-template
      ref: refs/tags/0.2

jobs:
  - template: run-tox-env.yml@tox
    parameters:
      tox_version: ""
      jobs:
        py312:
          image: [linux]

        py311:
          image: [linux]

        py310:
          image: [linux]

      # Publish test results for this job
      steps:
        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '**/TEST-*.xml'
          condition: succeededOrFailed()
          displayName: 'Publish Test Results'
