name: Build and Push Image

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the latest Git tag and commit hash
        run: |
          # Fetch the latest tag
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          
          # Get the first 7 characters of the commit hash
          short_sha=$(git rev-parse --short HEAD)
          echo "Commit SHA (short): $short_sha"
          echo "short_sha=$short_sha" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/htrflow:latest .

      - name: Tag the Docker image with Git tag and commit hash
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/htrflow:latest ${{ secrets.DOCKERHUB_USERNAME }}/htrflow:$latest_tag-$short_sha

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/htrflow:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/htrflow:$latest_tag-$short_sha
