name: Deploy Docs

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/uv
        with:
          python-version: '3.10'

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy docs with Mike
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          uv run mike deploy --push --update-aliases $latest_tag latest
