name: Automatic generating docs for 📦

on: workflow_dispatch


permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          
          key: ${{ github.ref }}
          
          path: .cache
      
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -e .
      - run: make docs_install
      - run: mkdocs gh-deploy --force
