name: Automatic Docs and Package Publishing

on:
  release:
    types: [ published ]

permissions:
  contents: write
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Publish to pypi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build --no-interaction
      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force

