name: GPU tests 

# Todo: 
# 1.setup self-hosted runner..
# # 2. set event on: 
# pull_request:
#     branches:
#       - main

on: workflow_dispatch


jobs:
  gpu-test:
    runs-on: [self-hosted,GPU] 
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"] #add more 3.* to test here

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry
        with:
          python-version: ${{ matrix.python-version }}
      - run: poetry run pytest -m "gpu"

